name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # - name: Copy repository contents via scp
    #   uses: appleboy/scp-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     KEY: ${{ secrets.SSHKEY }}
    #   with:
    #     source: "."
    #     target: "/var/www/moonly-services"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd /var/www/moonly-services && pwd

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: pwd

    # - name: Remove older dist folder
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script: rm -rf dist

    # - name: Update dependencies
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script: yarn

    # - name: Build
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script: yarn build

    # - name: Update pm2 service
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script: pm2 reload 0